repos:
  # python

  - repo: https://github.com/timothycrosley/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        args: ["--profile", "black"]
        additional_dependencies: [toml]

  - repo: https://github.com/python/black
    rev: "22.8.0"
    hooks:
      - id: black
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        args: ["--max-line-length", "80", "--ignore", "E203,W503"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.971"
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

  # common

  - repo: https://github.com/hadolint/hadolint
    rev: "v2.10.0"
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.32.2"
    hooks:
      - id: markdownlint-fix

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: "v0.8.0"
    hooks:
      - id: shellcheck
