name: mostime

on:
  push:
    paths:
      - "src"
      - "tests"
      - ".github/workflows/mostime.yml"

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src:tests
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests using pytest
        run: poetry run python3 -m pytest tests

      - name: Generate coverage report
        run: poetry run python3 -m pytest --cov=./coverage/reports/ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage1.xml,./coverage2.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
